lamp:
  image: yangpeilyn/lamp:basic
  container_name: web
  ports:
    - 8080:80
  environment:
    - ON_CREATE_DB=rires
    - SITENAME=rires
    # backup sql file (optional)
    - STARTUP_SQL=/mysql_backup/rires.sql
    - CODE_PATH=/var/www/reproducibleIR/
    - CRON_JOBS=/cronjobs/cronjobs
    - QUERY_PATH=/var/www/rise_files/queries/
    - INDEX_PATH=/var/www/rise_files/index/
    - JUDGEMENT_PATH=/var/www/rise_files/judgements/
  volumes:
    # Server files
    - /var/www/reproducibleIR/:/var/www/rires/public_html/
    # backup sql file path
    - /var/www/reproducibleIR/docker/:/mysql_backup/
    # cron jobs file path
    - /var/www/reproducibleIR/daemon/:/cronjobs/
    # For running the docker inside the docker container
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/bin/docker

